[package]
name = "book"
version = "0.3.0"
authors = ["Mathieu Aucejo"]
license = "MIT"
description = "Modèle de thèse pour le Cnam"
entrypoint = "src/book.typ"
categories = ["report"]
repository = "https://github.com/maucejo/Cnam_thesis_template"

[template]
path = "template"
entrypoint = "main.typ"


