[package]
name = "bookcls"
version = "0.1.0"
authors = ["Mathieu Aucejo"]
license = "MIT"
description = "Modèle de thèse ou de livre"
entrypoint = "src/book.typ"
categories = ["book", "model"]
repository = "https://github.com/maucejo/book_template"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnails/main.png"