[package]
name = "book"
version = "0.6.0"
authors = ["Mathieu Aucejo"]
license = "MIT"
description = "Modèle de thèse ou de livre"
entrypoint = "src/book.typ"
categories = ["report"]
repository = "https://github.com/maucejo/book_template"

[template]
path = "template"
entrypoint = "main.typ"


